# Generated by Django 5.0.2 on 2025-02-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_trending', models.BooleanField(default=False, verbose_name='em tendência')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='último uso')),
            ],
            options={
                'verbose_name': 'hashtag',
                'verbose_name_plural': 'hashtags',
                'ordering': ['-created_at'],
            },
        ),
    ]
